name: Update Package Cache
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron:  '0 0/6 * * *'
  repository_dispatch:
    types: rebuild-cache
jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Update package cache
        run: |
          npm --no-save --no-package-json install @qooxdoo/compiler
          npx qx config set github.token "${{ secrets.PAT }}"
          npx qx package update --verbose --search --all-versions --file cache.json
          if git diff --quiet --exit-code; then
            echo "No changes."
          else
            echo "changes found."
            echo "CREATE_PR=1" >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        if: ${{ env.CREATE_PR }}
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update package cache
          token: ${{ secrets.PAT }}
          title: Automated Cache Updates
          body: This is an auto-generated PR with updates to the package cache
          branch: update-cache

# https://github.com/marketplace/actions/merge-me
#      - name: Merge Pull Request if from trusted contributor
#        uses: ridedott/merge-me-action@v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.PAT }}
